services:
  mysql:
    image: mysql:8.0.30
    restart: always
    expose:
      - '3306'
    volumes:
      - development_secondary:/var/lib/mysql
    logging:
            driver: none
    ports:
      - "3311:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-e", "select 1"]
      interval: 1s
      timeout: 1s
      retries: 20