version: '3.8'

# Change for create new server:
# Path: server/development/principal
# Name: development_principal
# Create new folder, copy files, change names and ports
# Run on terminal with the new serve: cat server/development/principal/nginx.conf server/development/secondary/nginx.conf > nginx.conf

services:
  # --------------- Development Principal ---------------
  development_principal_mysql:
    env_file:
      - server/development/principal/mysql.env
    extends:
      file: server/development/principal/mysql.yml
      service: mysql

  development_principal_redis:
    extends:
      file: server/development/principal/redis.yml
      service: redis

  development_principal_sidekiq:
    build: .
    extends:
      file: server/development/principal/sidekiq.yml
      service: sidekiq
    env_file:
      - server/development/principal/sidekiq.env

  development_principal_rabbitmq:
    extends:
      file: server/development/principal/rabbitmq.yml
      service: rabbitmq
    env_file:
      - server/development/principal/rabbitmq.env

  development_principal_web:
    build: .
    extends:
      file: server/development/principal/web.yml
      service: web
    env_file:
      - server/development/principal/web.env
    depends_on:
      development_principal_redis: {"condition":"service_healthy"}
      development_principal_sidekiq: {"condition":"service_healthy"}
      development_principal_mysql: {"condition":"service_healthy"}
      development_principal_rabbitmq: {"condition":"service_healthy"}

  development_principal_nginx:
    build:
      context: .
      dockerfile: DockerFile.nginx
    depends_on:
      - development_principal_web
    ports:
      - 80:80
  # --------------- --------------------- ---------------

  # --------------- Development Secondary ---------------
  development_secondary_mysql:
    env_file:
      - server/development/secondary/mysql.env
    extends:
      file: server/development/secondary/mysql.yml
      service: mysql

  development_secondary_redis:
    extends:
      file: server/development/secondary/redis.yml
      service: redis

  development_secondary_sidekiq:
    build: .
    extends:
      file: server/development/secondary/sidekiq.yml
      service: sidekiq
    env_file:
      - server/development/secondary/sidekiq.env

  development_secondary_rabbitmq:
    extends:
      file: server/development/secondary/rabbitmq.yml
      service: rabbitmq
    env_file:
      - server/development/secondary/rabbitmq.env

  development_secondary_web:
    build: .
    extends:
      file: server/development/secondary/web.yml
      service: web
    env_file:
      - server/development/secondary/web.env
    depends_on:
      development_secondary_redis: {"condition":"service_healthy"}
      development_secondary_sidekiq: {"condition":"service_healthy"}
      development_secondary_mysql: {"condition":"service_healthy"}
      development_secondary_rabbitmq: {"condition":"service_healthy"}

  development_secondary_nginx:
    build:
      context: .
      dockerfile: DockerFile.nginx
    depends_on:
      - development_secondary_web
    ports:
      - 81:81
  # --------------- --------------------- ---------------

volumes:
  # --------------- Development Principal ---------------
  development_principal_mysql:
  development_principal_redis:
  development_principal_rabbitmq:
  # --------------- --------------------- ---------------

  # --------------- Development Secondary ---------------
  development_secondary_mysql:
  development_secondary_redis:
  development_secondary_rabbitmq:
  # --------------- --------------------- ---------------