version: '3.8'

# Change for create new server:
# Path: server/development/principal
# Name: development_principal
# Create new folder, copy files, change names and ports
# Run on terminal with the new serve: cat server/development/principal/nginx.conf server/development/secondary/nginx.conf > nginx.conf

services:
  # --------------- Development Principal ---------------
  development_principal_mysql:
    env_file:
      - server/development/principal/mysql.env
    extends:
      file: server/development/principal/mysql.yml
      service: mysql
    networks:
      - principal

  development_principal_redis:
    extends:
      file: server/development/principal/redis.yml
      service: redis
    networks:
      - principal

  development_principal_sidekiq:
    build: .
    extends:
      file: server/development/principal/sidekiq.yml
      service: sidekiq
    env_file:
      - server/development/principal/sidekiq.env
    networks:
      - principal

  development_principal_web:
    build: .
    extends:
      file: server/development/principal/web.yml
      service: web
    env_file:
      - server/development/principal/web.env
    depends_on:
      development_principal_redis: {"condition":"service_healthy"}
      development_principal_sidekiq: {"condition":"service_healthy"}
      development_principal_mysql: {"condition":"service_healthy"}
    networks:
      - principal
  # --------------- --------------------- ---------------

  # --------------- ------ Shared ------- ---------------
  nginx:
    build:
      context: .
      dockerfile: DockerFile.nginx
    depends_on:
      - development_principal_web

    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./log/nginx:/var/log/nginx
    networks:
      - principal
  # --------------- --------------------- ---------------

volumes:
  development_principal:

networks:
  principal: