version: '3.3'

services:
  web_hom_olimpia:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -b 0.0.0.0
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DB_USER: root
      DB_NAME: huge_tech
      DB_PASSWORD: 
      DB_HOST: mysql_hom_olimpia
      RAILS_MASTER_KEY: "OJc1SjyvpCD9alCF11OZyAUEaygWFkUJIaQs9HPklVfUWng96unk+4n5q9herBDXM4QnFvaRC+aebKYwyaxf0MNTAjrBi3FfURf5lfDNxHIAuSvOvumHmUXebeZXhAJDfAPe0mwXvow90uVUZcU9wAmbje19+jNMu6/rXNm/o6L5CBlYL2XpTpKiIPiH2gY9n6TwxijcMU42CA6w+56rjurCSD1mK7bJHb3OhKyBZsV7fsMQ+LabqZhNim4KrIUE7jjF+GAMYp0B28IiSXstJx99m+/7HCG2we0huI8tYgQrR0KPIZ0sgZqN3OCSSf0lL2LccNfxroydbRgD1WSAAjssDEftPpF2Uzfk8esqHQ4PpfX1Jv+X/Y2ZPZ+ls3NXg9Y0HhWnSKwWuAvY4NE2tpztnM/y--1rzc3wSd5qPPYQhL--x/7vvLnJ2PpC+NhlfQQbug=="
    depends_on:
      redis: {"condition":"service_healthy"}
      mysql_hom_olimpia: {"condition":"service_healthy"}
#      healthcheck:
#        test: ["CMD", "curl", "-SsfL", "127.0.0.1:3000"]
#        interval: 1s
#        timeout: 1s
#        retries: 300
  redis:
    image: redis:4.0-alpine
    restart: always
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
            driver: none
    depends_on:
      mysql_hom_olimpia: {"condition":"service_healthy"}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 300
  mysql_hom_olimpia:
    image: "mysql:8.0"
    restart: always
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
     MYSQL_USERNAME: root
    expose:
      - '3306'
    volumes:
      - mysql_hom_olimpia:/var/run/mysqld
    logging:
            driver: none
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-e", "select 1"]
      interval: 1s
      timeout: 1s
      retries: 300
  sidekiq:
    depends_on:
      - 'mysql_hom_olimpia'
      - 'redis'
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  # Demo
  web_demo:
  mysql_demo:
  redis:
  sidekiq:
  # Homolog Olímpia
  web_hom_olimpia:
  mysql_hom_olimpia:
  redis:
  sidekiq:
  # Homolog Santo André
  web_hom_olimpia:
  mysql_hom_olimpia:
  redis:
  sidekiq:
  # Homolog Suzano
  web_hom_olimpia:
  mysql_hom_olimpia:
  redis:
  sidekiq:
  # Homolog Extrema
  web_hom_olimpia:
  mysql_hom_olimpia:
  redis:
  sidekiq:
  # Homolog Cordeirópolis
  web_hom_olimpia:
  mysql_hom_olimpia:
  redis:
  sidekiq: