services:
  rabbitmq:
    image: rabbitmq:management
    ports:
        - 15672:15672
    volumes:
        - ~/.docker-conf/development_principal_rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/development_principal_rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
      interval: 1s
      timeout: 1s
      retries: 20