services:
  rabbitmq:
    image: rabbitmq:management
    ports:
        - 15673:15672
    volumes:
        - development_secondary:/var/lib/rabbitmq/
        #- development_secondary:/var/log/rabbitmq
    healthcheck:
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
      interval: 1s
      timeout: 1s
      retries: 20