services:
  rabbitmq:
    image: rabbitmq:management
    ports:
        - 15673:15672
    volumes:
        - ~/.docker-conf/development_secondary_rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/development_secondary_rabbitmq/log/:/var/log/rabbitmq